config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  devise_for :users

  resources :articles do
    member do
      put "approve", to: "articles#approve"
    end
  end


  resources :users do
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :authenticate_user!
    before_action :require_admin, only: [:destroy, :approve]

    def index
      @myarticles = Article.all.where(user_id: current_user.id)
      @myarticles = @myarticles.where(approved: true).reverse

      @unapproved_articles = Article.all.where(approved: false)
        # @articles =Article.all.where(approved: true).where.not(user_id: current_user.id)
        @articles = []
        all_users = User.order('approved_articles DESC').where.not(id: current_user.id)
        all_users.each do |user|
          user.articles.where(approved: true).reverse.each do |article|
          @articles << article
          end
        end
    end

    def new
        @article = Article.new   
    end

    def create
        @article = Article.new(article_params)
         
        @article.author_name = current_user.email.split('@')[0].capitalize!
        
        @article.user_id = current_user.id
        
        if @article.save
           
            redirect_to root_path
          else
            render 'new'
          end

    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      @author = User.where(id: @article.user_id).last
      if @article.approved? != true
         redirect_to root_path, :notice => "The article has been deleted"
      else
        @author.approved_articles -=1
        @author.save
        redirect_to root_path, :notice => "The article has been deleted"
      end
    end


    def approve
      @article = Article.find(params[:id])
      @article.toggle!(:approved)  
      @author = User.where(id: @article.user_id).last
      @author.approved_articles +=1
      @author.save

      redirect_to root_path, :notice => "The article has been approved"
    end


    private

def article_params
    params.require(:article).permit(:title , :description , :author_name)
  end
  def require_admin
		if current_user.admin? != true
			flash[:danger] = "You not allowed to do this only samir can do it"
			redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, url: articles_path) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <p>
    <%= form.label :title%>
    <br>
    <%= form.text_field :title, :id => 'title'  %>
  </p>

    <p>
    <%= form.label :description%>
    <br>
    <%= form.text_field :description, :id => 'body'  %>
  </p>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/index.html.erb
<div>
      <%if (current_user.admin? == true) && (@unapproved_articles.count > 0) %>
      <h1><td>pending for approve articles: <%=@unapproved_articles.count%></td></h1>
  <% @unapproved_articles.each do |article| %>
    <tr>
     <div  class="article">
      <h2 class="article-title"><td>author: <%= article.author_name %></td></h2>
      <h3 class="article-body"><td>title: <%= article.title %></td></h3>
      <h4 class="article-body"><td>description: <%= article.description %></td></h4>
       <% if current_user.admin? == true %>
       <span class="delete-button">
        <%= link_to "Delete", article_path(article.id), :confirm => "Are you sure?", :method => :delete %>
        </span>
        <%if article.approved? != true %>
        <span class="approve-button">
        <%= link_to "approve", approve_article_path(article.id), method: :put  %>
        </span>
        <% end %>
      <% end %>
      </div>
    </tr>
  <% end %>
  <% end %>
</div>
<div>
      <h1><td>Your approved articles</td></h1>
      <%if current_user.approved_articles == 0 %>
      You don't have any approved articles yet
      <% else %>
         <% @myarticles.each do |article| %>
         <tr>
          <div  class="article">
      <h2 class="article-title"><td>author: <%= article.author_name %></td></h2>
      <h3 class="article-body"><td>title: <%= article.title %></td></h3>
      <h4 class="article-body"><td>description: <%= article.description %></td></h4>
           <% if current_user.admin? == true %>
           <span class="delete-button">
          <%= link_to "Delete", article_path(article.id), :confirm => "Are you sure?", :method => :delete %>
          </span>
      <% end %>
      </div>
    </tr>
        <% end %>
    <% end %>
</div>

<div>
      <h1><td>Authors articles</td></h1>
  <% @articles.each do |article| %>
    <tr>
        <div  class="article">
      <h2 class="article-title"><td>author: <%= article.author_name %></td></h2>
      <h3 class="article-body"><td>title: <%= article.title %></td></h3>
      <h4 class="article-body"><td>description: <%= article.description %></td></h4>
       <% if current_user.admin? == true %>
       <span class="delete-button">
        <%= link_to "Delete", article_path(article.id), :confirm => "Are you sure?", :method => :delete %>
        </span>
      <% end %>
      </div>
    </tr>
  <% end %>
</div>


  <%= link_to 'New article', new_article_path %>
  

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>legen- wait for it-dary news</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="navbar-text" >
        <span class="logo"><strong>legen- wait for it-dary news</strong></span>
          <div class="right" >
            <% if user_signed_in? %>
              <table>
                <tbody>
                  <tr>
                    <td>Logged in as:</td>
                    <td><strong><%= current_user.email %></strong></td>
                    <td><div class="destroy-button"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></div></td>
                  </tr>
                </tbody>
              </table>
            <% end %>
          </div>
      </div>
    <%= yield %>
  </body>
</html>